
/* eslint-disable */
// this file is autogenerated by typewriter (used Template.tst file to generate)

import { AjaxProvider } from "../scripts/ajax";



export class PlayerDTO {
    Id: number = null;
    Name: string = null;
    Surname: string = null;
    BirthDate: Date = null;
    Height: number = null;
    Weight: number = null;
    Residence: string = null;
    Forehand: Forehand = null;
    Backhand: Backhand = null;
    Racquet: string = null;
    Surface: SurfaceType = null;
    FavouritePlayer: string = null;
    TitlesCount: number = null;
    FinalistCount: number = null;
    TournamentCount: number = null;
    Member: boolean = null;
    Points: number = null;
}
export class PlayerArgs {
    Id: number = null;
}
export class PlayerSearchArgs {
    SearchName: string = null;
}


export const enum Forehand {
    rightHanded = 0,
    leftHanded = 1
}
export const enum Backhand {
    oneHanded = 0,
    twoHanded = 1
}
export const enum SurfaceType {
    clay = 0,
    grass = 1,
    hard = 2
}

export default class PlayerClient {

    getWithoutParams<TResult extends PlayerDTO[]>(): Promise<TResult> {
        return AjaxProvider.apiGet("Player/PlayersByRanking", null);
    }

    getPlayerById<TArgs extends PlayerArgs, TResult extends PlayerDTO>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiGet("Player/PlayerById", data);
    }

    addOrEditPlayer<TArgs extends PlayerDTO, TResult extends any>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiPost("Player/AddOrEditPlayer", data);
    }

    playerBySearch<TArgs extends PlayerSearchArgs, TResult extends PlayerDTO[]>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiGet("Player/PlayerBySearch", data);
    }
}
