
/* eslint-disable */
// this file is autogenerated by typewriter (used Template.tst file to generate)

import { AjaxProvider } from "../scripts/ajax";



export class TournamentFilter {
    Id: number = null;
    Year: number = null;
    Type: TournamentType = null;
}
export class TournamentDTO {
    Id: number = null;
    Name: string = null;
    StartTime: Date = null;
    EndTime: Date = null;
    Place: string = null;
    Category: TournamentCategory = null;
    PlayingSystem: PlayingSystem = null;
    BallsType: BallsType = null;
    TournamentType: TournamentType = null;
    Surface: SurfaceType = null;
    Description: string = null;
}
export class TournamentByNameArgs {
    Name: string = null;
}


export const enum TournamentType {
    grandslam = 0,
    ata = 1,
    challanger = 2,
    ataSpecial = 3,
    challangerSpecial = 4
}
export const enum TournamentCategory {
    singles = 0,
    doubles = 1
}
export const enum PlayingSystem {
    complete = 0,
    prince = 1,
    kombi = 2,
    group = 3
}
export const enum BallsType {
    slazenger = 0,
    dunlop = 1
}
export const enum SurfaceType {
    clay = 0,
    grass = 1,
    hard = 2
}

export default class TournamentClient {

    get<TArgs extends TournamentFilter, TResult extends TournamentDTO[]>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiGet("Tournament", data);
    }

    getTournamentByName<TArgs extends TournamentByNameArgs, TResult extends TournamentDTO[]>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiGet("Tournament/getTournamentByName", data);
    }

    getWithoutParams<TResult extends TournamentDTO>(): Promise<TResult> {
        return AjaxProvider.apiGet("Tournament/nearestTournament", null);
    }

    addOrEditTournament<TArgs extends TournamentDTO, TResult extends TournamentDTO>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiPost("Tournament/AddOrEditTournament", data);
    }
}
