/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */

import { UserDTO } from "./dtos/UserDTO";
import { AjaxProvider } from "../scripts/ajax";


export class UserClient {
    authenticate<TArgs extends UserDTO, TResult extends UserDTO>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiPost("api/User/authenticate", data);
    }
    
    
    register<TArgs extends UserDTO, TResult extends any>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiPost("api/User/register", data);
    }
    
    getAll<TResult extends UserDTO[]>(): Promise<TResult> {
        return AjaxProvider.apiGet("api/User", null);
    }
    getById<TArgs extends number, TResult extends any>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiGet("api/User/id?id=${id}", data);
    }
    
    
    delete<TArgs extends number, TResult extends any>(data: TArgs): Promise<TResult> {
        return AjaxProvider.apiDelete("api/User/id?id=${id}", data);
    }
    
     
}