
  /* eslint-disable 
   this file is autogenerated by typewriter (used Template.tst file to generate) */

export const enum DrawSize 
{
    draw8 = 8,
    draw16 = 16,
    draw32 = 32,
    draw64 = 64,
}