
  /* eslint-disable 
   this file is autogenerated by typewriter (used Template.tst file to generate) */

export const enum PlayingSystem 
{
    complete = 0,
    prince = 1,
    kombi = 2,
    group = 3,
}