
/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */

export const enum TournamentType 
{
    grandslam = 0,
    ata = 1,
    challanger = 2,
    ataSpecial = 3,
    challangerSpecial = 4,
}