
  /* eslint-disable 
   this file is autogenerated by typewriter (used Template.tst file to generate) */

export const enum TournamentRound 
{
    round1 = 1,
    round2 = 2,
    round3 = 3,
    round4 = 4,
    round5 = 5,
    round6 = 6,
}