/* eslint-disable 
   this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { TournamentRound } from "../enums/TournamentRound";
            
      
      import { RoundMatchDTO } from "./RoundMatchDTO";
          
          

  export class DrawDTO {
        initialRound: TournamentRound = null;
        matchesCount: number = null;
        roundMatches: RoundMatchDTO[] = null;
    }