/* eslint-disable 
   this file is autogenerated by typewriter (used Template.tst file to generate) */



  export class EntryFeeDTO {
        id: number = null;
        fee: number = null;
        isMember: number = null;
    }