/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { MatchEntryDTO } from "./MatchEntryDTO";
          
          

  export class MatchDTO {
        id: number = null;
        round: number | null = null;
        winner: number | null = null;
        tournamentId: number = null;
        matchEntries: MatchEntryDTO[] = null;
    }