/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { ScoreDTO } from "./ScoreDTO";
          
          

  export class MatchEntryDTO {
        id: number = null;
        matchId: number = null;
        playerId: number | null = null;
        parentMatchId: number | null = null;
        scores: ScoreDTO[] = null;
    }