/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */



  export class PlayerDrawDTO {
        tournamentEntryId: number = null;
        playerId: number = null;
        name: string = null;
        surname: string = null;
    }