/* eslint-disable 
   this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { Forehand } from "../enums/Forehand";
            
      
      import { Backhand } from "../enums/Backhand";
            
      
      import { SurfaceType } from "../enums/SurfaceType";
            

  export class PlayerDTO {
        id: number = null;
        name: string = null;
        surname: string = null;
        birthDate: Date | null = null;
        height: number | null = null;
        weight: number | null = null;
        residence: string = null;
        forehand: Forehand | null = null;
        backhand: Backhand | null = null;
        racquet: string = null;
        surface: SurfaceType | null = null;
        favouritePlayer: string = null;
        titlesCount: number | null = null;
        finalistCount: number | null = null;
        tournamentCount: number | null = null;
        member: boolean | null = null;
        points: number | null = null;
    }