/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { MatchDTO } from "./MatchDTO";
          
          

  export class RoundMatchDTO {
        round: number = null;
        matches: MatchDTO[] = null;
    }