/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */



  export class ScoreDTO {
        id: number = null;
        setNumber: number = null;
        gamesWon: number = null;
        matchEntryId: number = null;
    }