/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */



  export class SearchedTournamentDTO {
        tournamentId: number = null;
        name: string = null;
        startTime: Date = null;
    }