/* eslint-disable 
   this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { TournamentDTO } from "./TournamentDTO";
          
          
      
      import { PlayerDrawDTO } from "./PlayerDrawDTO";
          
          
      
      import { DrawDTO } from "./DrawDTO";
          
          

  export class TournamentGraphDTO {
        tournament: TournamentDTO = null;
        players: PlayerDrawDTO[] = null;
        draw: DrawDTO = null;
    }