/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { TournamentType } from "../enums/TournamentType";
            

  export class TournamentFilterDTO {
        id: number | null = null;
        year: number | null = null;
        type: TournamentType | null = null;
    }