/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */


      
      import { TournamentDTO } from "./TournamentDTO";
          
          
      
      import { PlayerDTO } from "./PlayerDTO";
          
          

  export class TournamentEntryDTO {
        id: number = null;
        tournamentId: number = null;
        playerId: number = null;
        tournament: TournamentDTO = null;
        player: PlayerDTO = null;
    }