/* eslint-disable */
/* this file is autogenerated by typewriter (used Template.tst file to generate) */



  export class UserDTO {
        username: string = null;
        password: string = null;
        token: string = null;
    }